### ISSUE TITLE
class css

### ISSUE THREAD

**Issue by Lyumih** [Aruytehno/aruytehno.github.io#1]
Лучше использовать классы селекторов, а не HTML теги. 
Например, не body{}, а .body{}

<style type="text/css">
        body {
            background-image: url(images/aircraft.jpg);
            background-repeat: no-repeat;
            background-position: center 0px;
            margin: 0 auto;
            background-size: cover;
        }
        form {
            margin: 0 auto;
            margin-top: +20%;
        }
        h2 {
            font-family: Verdana, Arial, Helvetica, sans-serif;
            margin-bottom: +3%;
        }
        p {
            font-family: 'Times New Roman', Times, serif;
            font-style: italic;
        }
    </style>

**Comment by Aruytehno** [comment]
I don't understand) Please to new branch.

**Comment by Lyumih** [comment]
https://htmlacademy.ru/courses/4/run/11
